version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./public:/var/www/html
    ports:
      - '8000:80'
  php:
    build: .
    volumes:
      - ./:/var/www/html
    depends_on:
      - nginx
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: larave
      MYSQL_ROOT_PASSWORD: 